language: python
sudo: false
env:
 - DJANGO_VERSION=1.8
 - DJANGO_VERSION=1.9
 - DJANGO_VERSION=1.10
 - DJANGO_VERSION=1.11
 - DJANGO_VERSION=2.0b1
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "pypy"
install:
 - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -q python-memcached>=1.57; fi
 - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -q python3-memcached>=1.51; fi
 - if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install -q python-memcached>=1.57; fi
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99" flake8 django-redis==4.8.0
script:
 - ./run.sh test
 - ./run.sh flake8
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0b1
    - python: "pypy"
      env: DJANGO_VERSION=2.0b1
