language: python
env:
 - DJANGO="Django>=1.4,<1.4.99"
 - DJANGO="Django>=1.5,<1.5.99"
 - DJANGO="Django>=1.6,<1.6.99"
python:
 - "2.6"
 - "2.7"
install:
 - pip install -q ${DJANGO}
script: ./run.sh test
